### ISSUE TITLE
Plenty failing tests on cpantesters for version 0.024

### ISSUE THREAD

**Issue by andk** [Leont/extutils-hascompiler#15]
I cannot tell the reason for the broken tests, sorry. No statistics give me a hint about the reason, so probably there is some second-level dependency responsible that does not show up in the declared dependencies?

**Comment by Leont** [comment]
I have figured out the problem. Your perls were installed with libnsl available, but it no longer is. That means that effectively it can't build a new static perl. My code for detecting if one can still compile a (static) perl fails to detect that.

I should probably just skip that test on dynamic perls, there are too many issues with it really and it's not something anyone would realistically use anyway.

**Comment by Leont** [comment]
Issue is worked around in the latest release
